# Generated by Django 5.2 on 2025-04-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0002_rename_company_address_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=20)),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[
                            ("UN", "Unidade"),
                            ("LT", "Litros"),
                            ("KG", "Kilogramas"),
                        ],
                        max_length=2,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("value", models.DecimalField(decimal_places=2, max_digits=100000000)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_description", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Corretivo", "corretivo"),
                            ("Preventivo", "preventivo"),
                            ("Preditivo", "preditivo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=100000000)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=20)),
                ("plate_number", models.CharField(max_length=20)),
                ("km", models.DecimalField(decimal_places=2, max_digits=100000000)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os_number", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=100000000)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "item_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.itemsale",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budget.service"
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="budget.vehicle"
                    ),
                ),
            ],
        ),
    ]
