# Generated by Django 5.2 on 2025-04-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company_Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("neighborhood", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_name", models.CharField(max_length=50)),
                (
                    "cnpj",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("phone_number", models.CharField(max_length=10)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company_address",
                    ),
                ),
            ],
        ),
    ]
