# Generated by Django 5.1.4 on 2025-04-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_name', models.CharField(max_length=50, verbose_name='Razão social')),
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.address')),
            ],
        ),
    ]
