# Generated by Django 5.1.4 on 2025-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50, unique=True),
        ),
    ]
