# Generated by Django 5.1.4 on 2025-04-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.client')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente Jurídico',
                'verbose_name_plural': 'Clientes Jurídicos',
            },
            bases=('client.client',),
        ),
        migrations.CreateModel(
            name='IndividualClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.client')),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente Físico',
                'verbose_name_plural': 'Clientes Físicos',
            },
            bases=('client.client',),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
