# Generated by Django 5.1.4 on 2025-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_corporateclient_individualclient_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='individualclient',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
